import { unsafeSVG } from "lit/directives/unsafe-svg.js";
import { html } from "lit/static-html.js";
import {
    AlertTriangle,
    BetweenHorizontalStart,
    Brain,
    Check,
    CheckCheck,
    ChevronDown,
    CircleCheckBig,
    Code,
    Copy,
    CornerDownLeft,
    createElement,
    Download,
    FileText,
    Folder,
    GalleryHorizontalEnd,
    History,
    MessageCircleDashed,
    Minimize2,
    Paperclip,
    Pencil,
    Plus,
    Settings,
    Trash2,
    Upload,
    X,
} from "lucide";

const icon = (Icon: any) => ({
    small: html`${unsafeSVG(createElement(Icon, { width: 12, height: 12 }).outerHTML)}`,
    medium: html`${unsafeSVG(createElement(Icon, { width: 14, height: 14 }).outerHTML)}`,
    large: html`${unsafeSVG(createElement(Icon, { width: 18, height: 18 }).outerHTML)}`,
});

export const themeIcons = {
    alertTriangle: icon(AlertTriangle),
    betweenHorizontalStart: icon(BetweenHorizontalStart),
    brain: icon(Brain),
    check: icon(Check),
    checkCheck: icon(CheckCheck),
    chevronDown: icon(ChevronDown),
    circleCheckBig: icon(CircleCheckBig),
    code: icon(Code),
    compress: icon(Minimize2),
    copy: icon(Copy),
    download: icon(Download),
    enter: icon(CornerDownLeft),
    fileText: icon(FileText),
    folder: icon(Folder),
    gallery: icon(GalleryHorizontalEnd),
    ghostChat: icon(MessageCircleDashed),
    history: icon(History),
    paperclip: icon(Paperclip),
    pencil: icon(Pencil),
    plus: icon(Plus),
    settings: icon(Settings),
    trash: icon(Trash2),
    upload: icon(Upload),
    x: icon(X),
} as const;
